//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstStrikeLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FirstStrikeLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Config xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Name&gt;firststrike&lt;/Name&gt;
        ///  &lt;UpdatesUrl&gt;http://test.fsmod.com/&lt;/UpdatesUrl&gt;
        ///  &lt;ApplicationUpdatesFeed&gt;http://test.fsmod.com/launcher/UpdatesFeed.xml&lt;/ApplicationUpdatesFeed&gt;
        ///  &lt;UpdateBeforeLaunch&gt;true&lt;/UpdateBeforeLaunch&gt;
        ///  &lt;Options /&gt;
        ///  &lt;Arguments /&gt;
        ///  &lt;Resolutions&gt;
        ///    &lt;string&gt;800x600&lt;/string&gt;
        ///    &lt;string&gt;1024x768&lt;/string&gt;
        ///    &lt;string&gt;1280x720&lt;/stri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon FirstStrikeIcon {
            get {
                object obj = ResourceManager.GetObject("FirstStrikeIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FirstStrikeLogo {
            get {
                object obj = ResourceManager.GetObject("FirstStrikeLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gui
        ///First Strike Mod Website.url
        ///firststrike.ico
        ///launcherlist.txt
        ///launcherversion.txt
        ///library.zip
        ///mirrorlist.txt
        ///MSVCP71.DLL
        ///MSVCR71.dll
        ///news.txt
        ///uninst.exe
        ///update.exe
        ///updaterlist.txt
        ///updaterversion.txt
        ///w9xpopen.exe
        ///xfire.data.
        /// </summary>
        internal static string OldLauncherFiles {
            get {
                return ResourceManager.GetString("OldLauncherFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 800x600
        ///1024x768
        ///1280x720
        ///1280x960
        ///1366x768
        ///1400x1050
        ///1600x900
        ///1600x1200
        ///1680x1050
        ///1920x1080
        ///1920x1200.
        /// </summary>
        internal static string Resolutions {
            get {
                return ResourceManager.GetString("Resolutions", resourceCulture);
            }
        }
    }
}
